In [1]:
import numpy as np 
numpy_arr=np.load('Dataset/numpy/A.thaliana1000indep_neg/kmer_1.npy')
print(numpy_arr)

[[0.45833333 0.375      0.26315789 0.41666667]
 [0.375      0.375      0.57894737 0.25      ]
 [0.08333333 0.66666667 0.52631579 0.29166667]
 ...
 [0.41666667 0.125      0.63157895 0.41666667]
 [0.20833333 0.45833333 0.31578947 0.54166667]
 [0.5        0.25       0.36842105 0.41666667]]
